### PR TITLE
fix the bug about the ip checking in agent.createConnection

### PR DESCRIPTION
**Pull request by JASONPANGGO**
fix the bug about the ip checking in agent.createConnection

### CODE REVIEW

**Comment by lizheming** [comment]
hello, thank you for your pull request. could you tell me detaily what's problem before? It seems you bring host check forward connection callback.

**Comment by JASONPANGGO** [comment]
At 2019-10-30 17:57:01, "Austin Lee" <notifications@github.com> wrote:


hello, thank you for your pull request. could you tell me detaily what's problem before? It seems you bring host check forward connection callback.

**Comment by JASONPANGGO** [comment]
> hello, thank you for your pull request. could you tell me detaily what's problem before? It seems you bring host check forward connection callback.

Hi. The code before checks the host in the connection callback and kill the connection if the host doesn't pass the check. I think the checking should be done before the connection is initialized and if the check returns a falsy value then throw an error and stop creating a connection.

**Comment by lizheming** [comment]
OK, so it hasn't bug before, just have some place should be optimized, am I right? It's OK to bring address check forward connection creation. But there have some type lint error should be fixed and `checker()` method can be removed because just have one place use it after the pr merged. So I'll optimize code after merged, I hope you don't mind it.

**Comment by welefen** [comment]
`ssrf-agent@1.0.3` is published

**Pull request merged**
